#!/usr/bin/env python3
"""Generate the OpenGL 1.1 entry points for the Nintendo Switch build.

devkitPro's Mesa ships EGL + glapi but no libGL, so the plain GL 1.1 functions
that the renderer (and GLEW itself) call directly have no symbols to link
against. This script reads the GL 1.1 prototypes from the bundled glew.h and
emits one C++ file that:

  - defines every GL 1.1 function as a thin forwarder to a function pointer, and
  - provides SwitchGL_LoadCoreEntryPoints(), which fills those pointers with
    eglGetProcAddress() once a context is current (called from GLimp_Init).

Usage: gen_gl11_loader.py <path/to/glew.h> <output.cpp>
"""

from __future__ import annotations

import re
import sys

PROTOTYPE = re.compile(r"^GLAPI\s+(?P<ret>.+?)\s+GLAPIENTRY\s+(?P<name>gl\w+)\s*\((?P<params>.*)\);\s*$")
PARAM_NAME = re.compile(r"(\w+)\s*(\[\s*\d*\s*\])?\s*$")


def parse_prototypes(glew_header: str) -> list[tuple[str, str, str, list[str]]]:
    """Return (return type, name, parameter list, argument names) for GL 1.1."""
    in_gl11 = False
    prototypes = []
    with open(glew_header, encoding="latin-1") as header:
        for raw in header:
            line = raw.rstrip("\r\n")
            if line.startswith("#ifndef GL_VERSION_1_1"):
                in_gl11 = True
                continue
            if in_gl11 and line.startswith("#endif /* GL_VERSION_1_1 */"):
                break
            if not in_gl11:
                continue
            match = PROTOTYPE.match(line)
            if not match:
                continue
            params = match.group("params").strip()
            args: list[str] = []
            if params and params != "void":
                for param in params.split(","):
                    name = PARAM_NAME.search(param.strip())
                    if not name:
                        raise ValueError(f"cannot find parameter name in: {line}")
                    args.append(name.group(1))
            prototypes.append((match.group("ret").strip(), match.group("name"), params or "void", args))
    if not prototypes:
        raise ValueError(f"no GL 1.1 prototypes found in {glew_header}")
    return prototypes


def emit(prototypes: list[tuple[str, str, str, list[str]]], out_path: str) -> None:
    lines = [
        "// Generated by tools/switch/gen_gl11_loader.py from src/external/glew/glew.h.",
        "// Do not edit by hand.",
        "",
        '#include "../../external/glew/glew.h"',
        "#include <EGL/egl.h>",
        "",
        "namespace {",
    ]
    for ret, name, _params, _args in prototypes:
        lines.append(f"decltype( &::{name} ) p_{name} = nullptr;")
    lines += ["}", "", 'extern "C" {', ""]
    for ret, name, params, args in prototypes:
        call = f"p_{name}( {', '.join(args)} )" if args else f"p_{name}()"
        body = f"return {call};" if ret != "void" else f"{call};"
        lines.append(f"{ret} GLAPIENTRY {name}( {params} ) {{ {body} }}")
    lines += [
        "",
        "}",
        "",
        "// Resolves every GL 1.1 entry point through EGL. Needs a current context.",
        "// Returns the number of entry points that could not be resolved and stores",
        "// the first missing name in *firstMissing (when not null).",
        "int SwitchGL_LoadCoreEntryPoints( const char **firstMissing ) {",
        "\tint missing = 0;",
        "\tif ( firstMissing ) {",
        "\t\t*firstMissing = nullptr;",
        "\t}",
    ]
    for _ret, name, _params, _args in prototypes:
        lines += [
            f'\tp_{name} = reinterpret_cast<decltype( p_{name} )>( eglGetProcAddress( "{name}" ) );',
            f"\tif ( !p_{name} ) {{ if ( firstMissing && !*firstMissing ) {{ *firstMissing = \"{name}\"; }} missing++; }}",
        ]
    lines += ["\treturn missing;", "}", ""]
    with open(out_path, "w", encoding="utf-8", newline="\n") as out:
        out.write("\n".join(lines))


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    emit(parse_prototypes(argv[0]), argv[1])
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
