/*
===========================================================================

OpenPrey - Nintendo Switch platform layer (devkitPro libnx)

===========================================================================
*/

#ifndef __SWITCH_LOCAL_H__
#define __SWITCH_LOCAL_H__

// Root of the install on the SD card. It holds the retail Prey "base" folder,
// the OpenPrey "basepy" overlay, configs, saves and logs.
#define SWITCH_BASE_PATH		"sdmc:/switch/openprey"

// Event queue shared by input and console code (main thread only).
void		Switch_QueEvent( sysEventType_t type, int value, int value2, int ptrLength, void *ptr );

// CPU boost while loading (switch_main.cpp); calls nest.
void		Sys_SetLoadingBoost( bool enable );

// Threads (switch_threads.cpp).
void		Switch_InitThreads( void );
void		Switch_StartAsyncThread( void );
void		Switch_StopAsyncThread( void );

// Input (switch_input.cpp). Called from Sys_GenerateEvents on the main thread.
void		Switch_PollInput( void );
// Binds the controller keys the saved config leaves unbound. Call after common->Init.
void		Switch_ApplyDefaultBinds( void );

// GL 1.1 entry points (generated by tools/switch/gen_gl11_loader.py).
int			SwitchGL_LoadCoreEntryPoints( const char **firstMissing );

// The statically linked game module (see basepy/meson.build).
extern "C" gameExport_t *GetGameAPI( gameImport_t *import );

#endif /* !__SWITCH_LOCAL_H__ */
