/*
===========================================================================

OpenPrey - Nintendo Switch platform layer (devkitPro libnx)

===========================================================================
*/

#ifndef __SWITCH_LOCAL_H__
#define __SWITCH_LOCAL_H__

// Root of the install on the SD card. It holds the retail Prey "base" folder
// and the OpenPrey "basepr" overlay, where configs, saves, logs and the
// generated/ image cache are written.
#define SWITCH_BASE_PATH		"sdmc:/switch/openprey"

// Event queue shared by input and console code (engine thread only).
void		Switch_QueEvent( sysEventType_t type, int value, int value2, int ptrLength, void *ptr );

// CPU boost while loading (switch_main.cpp); calls nest.
void		Sys_SetLoadingBoost( bool enable );
// Clock profile (r_switchPerfProfile, switch_main.cpp). Check runs once per
// Sys_GenerateEvents and re-applies the profile when the system changed it.
void		Switch_ApplyPerformanceProfile( void );
void		Switch_CheckPerformanceProfile( void );
void		Switch_RestorePerformanceProfile( void );

// Threads (switch_threads.cpp).
void		Switch_InitThreads( void );
void		Switch_StartAsyncThread( void );
void		Switch_StopAsyncThread( void );
// Core for the next pthread_create only (default for all others: core 2). See switch_threads.cpp.
void		Switch_SetNextThreadCore( int core );

// Input (switch_input.cpp). Called from Sys_GenerateEvents on the engine thread.
void		Switch_PollInput( void );
// Binds the controller keys the saved config leaves unbound. Call after common->Init.
void		Switch_ApplyDefaultBinds( void );
// Queues a relative mouse move (M_DELTAX/M_DELTAY) for idUsercmdGen (switch_input.cpp).
void		Switch_QueueMouseDelta( int dx, int dy );

// Gyro aiming (switch_gyro.cpp). Switch_UpdateGyro runs once per input poll on the
// engine thread: gameplay tells it whether look input is live, whether the aim
// button is held, and which controller layout is active (padIsHandheld /
// padGetStyleSet), and it queues the rotation as mouse deltas.
void		Switch_InitGyro( void );
void		Switch_UpdateGyro( bool gameplay, bool aimHeld, bool handheld, unsigned int npadStyleSet );
// Stops the six-axis sensors; the process must not end with them running.
void		Switch_ShutdownGyro( void );

// Milliseconds spent in eglSwapBuffers since the last call (switch_glimp.cpp).
float		Switch_TakeSwapMsec( void );
// r_fpsLock: sleeps between main loop frames to hold the locked frame rate.
void		Switch_PaceFrame( void );

// GL 1.1 entry points (generated by tools/switch/gen_gl11_loader.py).
int			SwitchGL_LoadCoreEntryPoints( const char **firstMissing );

// The statically linked game module (see basepy/meson.build).
extern "C" gameExport_t *GetGameAPI( gameImport_t *import );

#endif /* !__SWITCH_LOCAL_H__ */
